import { RoomId, SessionKind, Speaker, TrackId } from '../sessions/entities/session.entity';

export interface SeedSession {
  id: string;
  day: number;
  title: string;
  description: string | null;
  startUtc: string;
  endUtc: string;
  room: RoomId;
  track: TrackId | null;
  kind: SessionKind;
  fullWidth?: boolean;
  speakers: Speaker[];
}

/**
 * StartFEST 2026 agenda.
 *
 * Wall-clock times in the printed programme are Mountain Daylight Time
 * (UTC-6); every instant below is the UTC equivalent. Nothing downstream
 * re-derives the offset -- the UTC instant is the single source of truth.
 */
const D1 = '2026-06-23';
const D2 = '2026-06-24';

const at = (day: string, hhmm: string) => `${day}T${hhmm}:00.000Z`;

export const AGENDA_SEED: SeedSession[] = [
  // ------------------------------------------------------------------ DAY 1
  {
    id: 'd1-welcome',
    day: 1,
    title: 'Welcome',
    description: null,
    startUtc: at(D1, '15:00'),
    endUtc: at(D1, '15:15'),
    room: 'mainstage',
    track: null,
    kind: 'mainstage',
    fullWidth: true,
    speakers: [{ name: 'Clint Betts' }, { name: 'Lindsey Ivie' }],
  },
  {
    id: 'd1-opening-keynote',
    day: 1,
    title: 'Opening Keynote',
    description: null,
    startUtc: at(D1, '15:15'),
    endUtc: at(D1, '15:45'),
    room: 'mainstage',
    track: null,
    kind: 'keynote',
    fullWidth: true,
    speakers: [
      {
        name: 'Nick Thomas',
        title: 'CEO Nordmark, Co-founded Bluetooth Special Interest Group',
      },
    ],
  },
  {
    id: 'd1-state-of-slopes',
    day: 1,
    title: 'The State of Silicon Slopes: Where the Money Is Moving',
    description: null,
    startUtc: at(D1, '15:45'),
    endUtc: at(D1, '16:15'),
    room: 'mainstage',
    track: null,
    kind: 'mainstage',
    fullWidth: true,
    speakers: [
      { name: 'Ryan Caldwell', title: 'CEO MX' },
      { name: 'Tara Rosander', title: 'Deputy Director, COO GOED' },
    ],
  },
  {
    id: 'd1-bridging-the-gap',
    day: 1,
    title: 'Bridging the Gap',
    description: null,
    startUtc: at(D1, '16:30'),
    endUtc: at(D1, '17:05'),
    room: 'start',
    track: 'funding',
    kind: 'session',
    speakers: [
      { name: 'Scott Holley', title: 'Executive Director, Lassonde Entrepreneur Institute' },
    ],
  },
  {
    id: 'd1-surviving-ai-correction',
    day: 1,
    title: 'Surviving the AI Correction',
    description: null,
    startUtc: at(D1, '16:30'),
    endUtc: at(D1, '17:05'),
    room: 'start',
    track: 'ai',
    kind: 'session',
    speakers: [{ name: 'Michael Malin', title: 'Founder Model Forge' }],
  },
  {
    id: 'd1-cant-scale-regulate',
    day: 1,
    title: 'You Cannot Scale What You Cannot Regulate',
    description: null,
    startUtc: at(D1, '16:30'),
    endUtc: at(D1, '17:05'),
    room: 'ignition',
    track: 'selfLeadership',
    kind: 'session',
    speakers: [
      {
        name: 'Lisa Jones Christensen',
        title: 'Associate Professor of Entrepreneurship, Marriott School of Business, BYU',
      },
    ],
  },
  {
    id: 'd1-ai-blueprint-workshop',
    day: 1,
    title: 'AI Blueprint Workshop',
    description: null,
    startUtc: at(D1, '16:30'),
    endUtc: at(D1, '17:05'),
    room: 'accelerator',
    track: 'ai',
    kind: 'session',
    speakers: [{ name: 'Cameo Doran', title: 'Founder Cameo Labs' }],
  },
  {
    id: 'd1-break-1',
    day: 1,
    title: 'Break',
    description: null,
    startUtc: at(D1, '17:05'),
    endUtc: at(D1, '17:25'),
    room: 'mainstage',
    track: null,
    kind: 'break',
    fullWidth: true,
    speakers: [],
  },
  {
    id: 'd1-ai-not-your-cmo',
    day: 1,
    title: 'AI Is Not Your CMO: The New GTM Math',
    description: null,
    startUtc: at(D1, '17:25'),
    endUtc: at(D1, '18:00'),
    room: 'start',
    track: 'sales',
    kind: 'session',
    speakers: [{ name: 'Joe Grover', title: 'CGO Ampleo' }],
  },
  {
    id: 'd1-funding',
    day: 1,
    title: 'Funding',
    description: null,
    startUtc: at(D1, '17:25'),
    endUtc: at(D1, '18:00'),
    room: 'ignition',
    track: 'funding',
    kind: 'session',
    speakers: [{ name: 'Brock Blake', title: 'CEO Lendio' }],
  },
  {
    id: 'd1-even-achieving',
    day: 1,
    title: 'Even-Achieving: How to Balance Stress with Success',
    description: null,
    startUtc: at(D1, '17:25'),
    endUtc: at(D1, '18:00'),
    room: 'accelerator',
    track: 'selfLeadership',
    kind: 'session',
    speakers: [{ name: 'Erika Coleman', title: 'Erika Coleman Speaks' }],
  },
  {
    id: 'd1-lunch',
    day: 1,
    title: 'Networking Lunch',
    description: null,
    startUtc: at(D1, '18:00'),
    endUtc: at(D1, '19:30'),
    room: 'mainstage',
    track: null,
    kind: 'break',
    fullWidth: true,
    speakers: [],
  },
  {
    id: 'd1-content-people-watch',
    day: 1,
    title: 'How to Make Content People Actually Want to Watch',
    description: null,
    startUtc: at(D1, '19:30'),
    endUtc: at(D1, '20:05'),
    room: 'start',
    track: 'marketing',
    kind: 'session',
    speakers: [{ name: 'Levi Lindsay', title: 'VP of Creative Pestie' }],
  },
  {
    id: 'd1-ai-c-suite',
    day: 1,
    title: 'AI for the C-Suite',
    description: null,
    startUtc: at(D1, '19:30'),
    endUtc: at(D1, '20:05'),
    room: 'ignition',
    track: 'ai',
    kind: 'session',
    speakers: [{ name: 'Landon Essig', title: 'CEO CoDev' }],
  },
  {
    id: 'd1-advisory-board',
    day: 1,
    title: 'Build an Advisory Board to Strengthen Fundraising',
    description: null,
    startUtc: at(D1, '19:30'),
    endUtc: at(D1, '20:05'),
    room: 'accelerator',
    track: 'funding',
    kind: 'session',
    speakers: [
      { name: 'Nicole Toomey Davis', title: 'President & CEO and Co-Founder Enclavix, LLC' },
    ],
  },
  {
    id: 'd1-leadership-daly',
    day: 1,
    title: 'Leadership',
    description: null,
    startUtc: at(D1, '20:15'),
    endUtc: at(D1, '21:00'),
    room: 'start',
    track: 'selfLeadership',
    kind: 'session',
    speakers: [{ name: 'Steve Daly', title: 'CEO Instructure' }],
  },
  {
    id: 'd1-comp-plan-pipeline',
    day: 1,
    title: 'Your Comp Plan Is Killing Your Pipeline',
    description: null,
    startUtc: at(D1, '20:15'),
    endUtc: at(D1, '21:00'),
    room: 'ignition',
    track: 'sales',
    kind: 'session',
    speakers: [{ name: 'Amy Cook', title: 'CMO Fullcast' }],
  },
  {
    id: 'd1-build-business-with-ai',
    day: 1,
    title: 'How to Build a Business with AI',
    description: null,
    startUtc: at(D1, '20:15'),
    endUtc: at(D1, '21:00'),
    room: 'accelerator',
    track: 'ai',
    kind: 'session',
    speakers: [{ name: 'Jon Cheney', title: 'CEO GENAIPI' }],
  },
  {
    id: 'd1-break-2',
    day: 1,
    title: 'Break',
    description: null,
    startUtc: at(D1, '21:00'),
    endUtc: at(D1, '21:15'),
    room: 'mainstage',
    track: null,
    kind: 'break',
    fullWidth: true,
    speakers: [],
  },
  {
    id: 'd1-leadership-arntz',
    day: 1,
    title: 'Leadership',
    description: null,
    startUtc: at(D1, '21:15'),
    endUtc: at(D1, '22:00'),
    room: 'start',
    track: 'selfLeadership',
    kind: 'session',
    speakers: [{ name: 'Steve Arntz', title: 'CEO Campire' }],
  },
  {
    id: 'd1-hackathon',
    day: 1,
    title: 'Hackathon',
    description: null,
    startUtc: at(D1, '21:15'),
    endUtc: at(D1, '23:00'),
    room: 'ignition',
    track: null,
    kind: 'special',
    speakers: [],
  },

  // ------------------------------------------------------------------ DAY 2
  {
    id: 'd2-opening-keynote',
    day: 2,
    title: 'AI and the Future of Utah',
    description: null,
    startUtc: at(D2, '14:45'),
    endUtc: at(D2, '15:15'),
    room: 'mainstage',
    track: null,
    kind: 'keynote',
    fullWidth: true,
    speakers: [
      { name: 'Jeremy Andrus', title: 'CEO Traeger' },
      { name: 'Clint Betts', title: 'CEO Silicon Slopes' },
    ],
  },
  {
    id: 'd2-startup-world-cup',
    day: 2,
    title: 'Startup World Cup - 10 Finalists',
    description: null,
    startUtc: at(D2, '15:15'),
    endUtc: at(D2, '16:50'),
    room: 'mainstage',
    track: null,
    kind: 'mainstage',
    fullWidth: true,
    speakers: [],
  },
  {
    id: 'd2-chaos-to-process',
    day: 2,
    title: 'From Chaos to Process',
    description: null,
    startUtc: at(D2, '17:00'),
    endUtc: at(D2, '17:35'),
    room: 'start',
    track: 'operations',
    kind: 'session',
    speakers: [{ name: 'Jake Fackrell', title: 'COO Savvos Health' }],
  },
  {
    id: 'd2-ai-automation',
    day: 2,
    title: 'AI Automation',
    description: null,
    startUtc: at(D2, '17:00'),
    endUtc: at(D2, '17:35'),
    room: 'ignition',
    track: 'ai',
    kind: 'session',
    speakers: [{ name: 'Gabe Larsen', title: 'Atonom' }],
  },
  {
    id: 'd2-ai-growth-marketing',
    day: 2,
    title: 'AI-Powered Growth Marketing',
    description: null,
    startUtc: at(D2, '17:00'),
    endUtc: at(D2, '17:35'),
    room: 'accelerator',
    track: 'sales',
    kind: 'session',
    speakers: [{ name: 'Michael Schmutz', title: 'Founder DataXGrowth' }],
  },
  {
    id: 'd2-room-owes-you-nothing',
    day: 2,
    title: 'The Room Owes You Nothing: Leading Without a Resume',
    description: null,
    startUtc: at(D2, '17:40'),
    endUtc: at(D2, '18:15'),
    room: 'start',
    track: 'selfLeadership',
    kind: 'session',
    speakers: [
      { name: 'Kurt Workman', title: 'CEO Owlet' },
      { name: 'Clint Betts', title: 'CEO Silicon Slopes' },
    ],
  },
  {
    id: 'd2-unexpected-obvious-growth',
    day: 2,
    title: 'The Unexpected Obvious of Growth: Conferences, Podcasts & Thought Leadership',
    description: null,
    startUtc: at(D2, '17:40'),
    endUtc: at(D2, '18:15'),
    room: 'ignition',
    track: 'marketing',
    kind: 'session',
    speakers: [{ name: 'Zack Oates', title: 'Founder & CEO, Ovation' }],
  },
  {
    id: 'd2-event-marketing',
    day: 2,
    title: 'Event Marketing',
    description: null,
    startUtc: at(D2, '17:40'),
    endUtc: at(D2, '18:15'),
    room: 'accelerator',
    track: 'marketing',
    kind: 'session',
    speakers: [
      { name: 'Catherine Bennett', title: 'Utah Business' },
      { name: 'Hayden Harward', title: 'Utah Business' },
      { name: 'Kolleen Russo', title: 'Utah Business' },
    ],
  },
  {
    id: 'd2-lunch',
    day: 2,
    title: 'Networking Lunch',
    description: null,
    startUtc: at(D2, '18:30'),
    endUtc: at(D2, '20:00'),
    room: 'mainstage',
    track: null,
    kind: 'break',
    fullWidth: true,
    speakers: [],
  },
  {
    id: 'd2-stop-producing-noise',
    day: 2,
    title: 'Stop Producing Noise. Start Building Signal',
    description: null,
    startUtc: at(D2, '20:00'),
    endUtc: at(D2, '20:35'),
    room: 'start',
    track: 'marketing',
    kind: 'session',
    speakers: [{ name: 'Krista Parry', title: 'Founder KP Media' }],
  },
  {
    id: 'd2-pydantic-n8n',
    day: 2,
    title: 'Building Reliable AI Workflow Automations with Pydantic & n8n',
    description: null,
    startUtc: at(D2, '20:00'),
    endUtc: at(D2, '20:35'),
    room: 'ignition',
    track: 'ai',
    kind: 'session',
    speakers: [{ name: 'Jordan Gunderson', title: 'Izeni Co-Founder' }],
  },
  {
    id: 'd2-teams-stop-talking',
    day: 2,
    title: 'When Teams Stop Talking, Data Stops Working',
    description: null,
    startUtc: at(D2, '20:00'),
    endUtc: at(D2, '20:35'),
    room: 'accelerator',
    track: 'operations',
    kind: 'session',
    speakers: [{ name: 'Russ Hannig', title: 'COO SponsorCX' }],
  },
  {
    id: 'd2-sustainable-ai',
    day: 2,
    title: 'Sustainable AI and the rise of the Mega Data Centers',
    description: 'Panel Discussion',
    startUtc: at(D2, '20:40'),
    endUtc: at(D2, '21:40'),
    room: 'start',
    track: 'ai',
    kind: 'session',
    speakers: [{ name: 'Brian Beutler', title: 'CEO Alianza' }],
  },
  {
    id: 'd2-open-office-hours',
    day: 2,
    title: 'Open Office Hours',
    description: 'Resource partners in Marketing, Sales, Legal, Accounting, and Fund Raising',
    startUtc: at(D2, '20:40'),
    endUtc: at(D2, '21:15'),
    room: 'ignition',
    track: 'resource',
    kind: 'special',
    speakers: [],
  },
  {
    id: 'd2-building-community',
    day: 2,
    title: 'Building Community in the Age of AI',
    description: null,
    startUtc: at(D2, '20:40'),
    endUtc: at(D2, '21:15'),
    room: 'accelerator',
    track: 'marketing',
    kind: 'session',
    speakers: [
      { name: 'Sindee Savage', title: 'Community Architech, Sindee Savage Consulting' },
    ],
  },
  {
    id: 'd2-million-dollar-video',
    day: 2,
    title: 'The Million Dollar Video Ad Framework',
    description: null,
    startUtc: at(D2, '21:20'),
    endUtc: at(D2, '22:00'),
    room: 'ignition',
    track: 'marketing',
    kind: 'session',
    speakers: [{ name: 'Jake Larsen', title: 'Founder Video Power Marketing' }],
  },
  {
    id: 'd2-grinding-to-growing',
    day: 2,
    title: 'From Grinding to Growing: Architect Your Capacity Wall',
    description: null,
    startUtc: at(D2, '21:20'),
    endUtc: at(D2, '22:00'),
    room: 'accelerator',
    track: 'selfLeadership',
    kind: 'session',
    speakers: [
      { name: 'Russ Simon', title: 'Founder Russ Simon Leadership Solutions' },
    ],
  },
];
